export type AnimalCategory = 'all' | 'farm' | 'wild' | 'sea' | 'birds' | 'bugs';

export interface Animal {
  id: string;
  name: string;
  emoji: string;
  category: 'farm' | 'wild' | 'sea' | 'birds' | 'bugs';
  imageUrl: string;
  soundType: string;
  funFact: string;
}

export interface Habitat {
  id: AnimalCategory;
  name: string;
  emoji: string;
  bgGradient: string;
}

export const HABITATS: Habitat[] = [
  {
    id: 'all',
    name: 'All',
    emoji: '🐾',
    bgGradient: 'bg-slate-50',
  },
  {
    id: 'farm',
    name: 'Farm',
    emoji: '🚜',
    bgGradient: 'bg-emerald-50/40',
  },
  {
    id: 'wild',
    name: 'Wild',
    emoji: '🦁',
    bgGradient: 'bg-amber-50/40',
  },
  {
    id: 'sea',
    name: 'Sea',
    emoji: '🌊',
    bgGradient: 'bg-sky-50/40',
  },
  {
    id: 'birds',
    name: 'Birds',
    emoji: '🦜',
    bgGradient: 'bg-rose-50/40',
  },
  {
    id: 'bugs',
    name: 'Bugs',
    emoji: '🐛',
    bgGradient: 'bg-lime-50/40',
  },
];

export const ANIMALS: Animal[] = [
  // ==================== FARM ANIMALS ====================
  {
    id: 'cow',
    name: 'Cow',
    emoji: '🐮',
    category: 'farm',
    imageUrl: '/assets/animals/cow.jpg',
    soundType: 'cow',
    funFact: 'Cows eat grass and produce fresh milk.',
  },
  {
    id: 'pig',
    name: 'Pig',
    emoji: '🐷',
    category: 'farm',
    imageUrl: '/assets/animals/pig.jpg',
    soundType: 'pig',
    funFact: 'Pigs are highly intelligent animals with an excellent sense of smell.',
  },
  {
    id: 'sheep',
    name: 'Sheep',
    emoji: '🐑',
    category: 'farm',
    imageUrl: '/assets/animals/sheep.jpg',
    soundType: 'sheep',
    funFact: 'Sheep have thick wool coats that keep them warm in cold weather.',
  },
  {
    id: 'horse',
    name: 'Horse',
    emoji: '🐴',
    category: 'farm',
    imageUrl: '/assets/animals/horse.jpg',
    soundType: 'horse',
    funFact: 'Horses can sleep both lying down and standing up.',
  },
  {
    id: 'duck',
    name: 'Duck',
    emoji: '🦆',
    category: 'farm',
    imageUrl: '/assets/animals/duck.jpg',
    soundType: 'duck',
    funFact: 'Ducks have waterproof feathers and webbed feet for swimming.',
  },
  {
    id: 'chicken',
    name: 'Chicken',
    emoji: '🐔',
    category: 'farm',
    imageUrl: '/assets/animals/chicken.jpg',
    soundType: 'chicken',
    funFact: 'Chickens communicate with over thirty distinct vocal sounds.',
  },
  {
    id: 'dog',
    name: 'Dog',
    emoji: '🐶',
    category: 'farm',
    imageUrl: '/assets/animals/dog.jpg',
    soundType: 'dog',
    funFact: 'Dogs have an extraordinary sense of smell up to 100,000 times stronger than humans.',
  },
  {
    id: 'cat',
    name: 'Cat',
    emoji: '🐱',
    category: 'farm',
    imageUrl: '/assets/animals/cat.jpg',
    soundType: 'cat',
    funFact: 'Cats can rotate their ears 180 degrees to detect faint sounds.',
  },
  {
    id: 'frog',
    name: 'Frog',
    emoji: '🐸',
    category: 'farm',
    imageUrl: '/assets/animals/frog.jpg',
    soundType: 'frog',
    funFact: 'Frogs absorb water directly through their skin rather than drinking it.',
  },

  // ==================== WILD ANIMALS ====================
  {
    id: 'lion',
    name: 'Lion',
    emoji: '🦁',
    category: 'wild',
    imageUrl: '/assets/animals/lion.jpg',
    soundType: 'lion',
    funFact: 'A lion roar can be heard from up to eight kilometres away.',
  },
  {
    id: 'tiger',
    name: 'Tiger',
    emoji: '🐯',
    category: 'wild',
    imageUrl: '/assets/animals/tiger.jpg',
    soundType: 'tiger',
    funFact: 'Tigers are the largest cat species and are strong swimmers.',
  },
  {
    id: 'elephant',
    name: 'Elephant',
    emoji: '🐘',
    category: 'wild',
    imageUrl: '/assets/animals/elephant.jpg',
    soundType: 'elephant',
    funFact: 'Elephants are the largest land animals and have remarkable memories.',
  },
  {
    id: 'giraffe',
    name: 'Giraffe',
    emoji: '🦒',
    category: 'wild',
    imageUrl: '/assets/animals/giraffe.jpg',
    soundType: 'giraffe',
    funFact: 'Giraffes are the tallest mammals in the world, with legs longer than most humans.',
  },
  {
    id: 'cheetah',
    name: 'Cheetah',
    emoji: '🐆',
    category: 'wild',
    imageUrl: '/assets/animals/cheetah.jpg',
    soundType: 'cheetah',
    funFact: 'Cheetahs are the fastest land animals, reaching speeds of up to 110 kilometres per hour.',
  },
  {
    id: 'hippo',
    name: 'Hippo',
    emoji: '🦛',
    category: 'wild',
    imageUrl: '/assets/animals/hippo.jpg',
    soundType: 'hippo',
    funFact: 'Hippos spend most of the day submerged in water to keep their skin cool.',
  },
  {
    id: 'chimp',
    name: 'Chimpanzee',
    emoji: '🐒',
    category: 'wild',
    imageUrl: '/assets/animals/chimp.jpg',
    soundType: 'monkey',
    funFact: 'Chimpanzees use tools such as sticks and stones to find food.',
  },
  {
    id: 'zebra',
    name: 'Zebra',
    emoji: '🦓',
    category: 'wild',
    imageUrl: '/assets/animals/zebra.jpg',
    soundType: 'zebra',
    funFact: 'Every zebra has a completely unique pattern of black and white stripes.',
  },
  {
    id: 'bear',
    name: 'Bear',
    emoji: '🐻',
    category: 'wild',
    imageUrl: '/assets/animals/bear.jpg',
    soundType: 'bear',
    funFact: 'Bears have an acute sense of smell and can hibernate through winter.',
  },
  {
    id: 'wolf',
    name: 'Wolf',
    emoji: '🐺',
    category: 'wild',
    imageUrl: '/assets/animals/wolf.jpg',
    soundType: 'wolf',
    funFact: 'Wolves live and hunt in family packs led by an alpha pair.',
  },

  // ==================== SEA ANIMALS ====================
  {
    id: 'dolphin',
    name: 'Dolphin',
    emoji: '🐬',
    category: 'sea',
    imageUrl: '/assets/animals/dolphin.jpg',
    soundType: 'dolphin',
    funFact: 'Dolphins use echolocation clicks to navigate and hunt in murky water.',
  },
  {
    id: 'blue-whale',
    name: 'Blue Whale',
    emoji: '🐋',
    category: 'sea',
    imageUrl: '/assets/animals/blue-whale.jpg',
    soundType: 'whale',
    funFact: 'The blue whale is the largest known animal ever to have lived on Earth.',
  },
  {
    id: 'clownfish',
    name: 'Clownfish',
    emoji: '🐠',
    category: 'sea',
    imageUrl: '/assets/animals/clownfish.jpg',
    soundType: 'clownfish',
    funFact: 'Clownfish have a special mucus coat that protects them from sea anemone stings.',
  },
  {
    id: 'sea-turtle',
    name: 'Sea Turtle',
    emoji: '🐢',
    category: 'sea',
    imageUrl: '/assets/animals/sea-turtle.jpg',
    soundType: 'turtle',
    funFact: 'Sea turtles can hold their breath underwater for several hours.',
  },
  {
    id: 'shark',
    name: 'Shark',
    emoji: '🦈',
    category: 'sea',
    imageUrl: '/assets/animals/shark.jpg',
    soundType: 'shark',
    funFact: 'Sharks have skeletons made entirely of cartilage rather than bone.',
  },
  {
    id: 'octopus',
    name: 'Octopus',
    emoji: '🐙',
    category: 'sea',
    imageUrl: '/assets/animals/octopus.jpg',
    soundType: 'octopus',
    funFact: 'An octopus has three hearts and blue copper-based blood.',
  },
  {
    id: 'sea-otter',
    name: 'Sea Otter',
    emoji: '🦦',
    category: 'sea',
    imageUrl: '/assets/animals/sea-otter.jpg',
    soundType: 'otter',
    funFact: 'Sea otters hold paws while floating to prevent drifting apart in ocean currents.',
  },
  {
    id: 'jellyfish',
    name: 'Jellyfish',
    emoji: '🪼',
    category: 'sea',
    imageUrl: '/assets/animals/jellyfish.jpg',
    soundType: 'jellyfish',
    funFact: 'Jellyfish are made of 95% water and have existed for over 500 million years.',
  },

  // ==================== BIRDS ====================
  {
    id: 'toucan',
    name: 'Toucan',
    emoji: '🦚',
    category: 'birds',
    imageUrl: '/assets/animals/toucan.jpg',
    soundType: 'toucan',
    funFact: 'A toucan bill is light and hollow, helping regulate its body temperature.',
  },
  {
    id: 'macaw',
    name: 'Macaw',
    emoji: '🦜',
    category: 'birds',
    imageUrl: '/assets/animals/macaw.jpg',
    soundType: 'macaw',
    funFact: 'Macaws can live for over 50 years and are known for mimicry and intelligence.',
  },
  {
    id: 'flamingo',
    name: 'Flamingo',
    emoji: '🦩',
    category: 'birds',
    imageUrl: '/assets/animals/flamingo.jpg',
    soundType: 'flamingo',
    funFact: 'Flamingos get their pink color from natural pigments in their diet.',
  },
  {
    id: 'owl',
    name: 'Owl',
    emoji: '🦉',
    category: 'birds',
    imageUrl: '/assets/animals/owl.jpg',
    soundType: 'owl',
    funFact: 'Owls have specialised feathers that enable near-silent flight.',
  },
  {
    id: 'eagle',
    name: 'Eagle',
    emoji: '🦅',
    category: 'birds',
    imageUrl: '/assets/animals/eagle.jpg',
    soundType: 'eagle',
    funFact: 'Eagles have powerful vision capable of spotting prey miles away.',
  },
  {
    id: 'puffin',
    name: 'Puffin',
    emoji: '🐧',
    category: 'birds',
    imageUrl: '/assets/animals/puffin.jpg',
    soundType: 'puffin',
    funFact: 'Puffins can dive up to 60 metres underwater to catch small fish.',
  },

  // ==================== NEW ANIMALS ====================
  {
    id: 'goat',
    name: "Goat",
    emoji: '🐐',
    category: 'farm',
    imageUrl: '/assets/animals/goat.jpg',
    soundType: 'goat',
    funFact: "Goats were one of the first animals to be tamed by humans and were being herded 9,000 years ago.",
  },
  {
    id: 'donkey',
    name: "Donkey",
    emoji: '🫏',
    category: 'farm',
    imageUrl: '/assets/animals/donkey.jpg',
    soundType: 'donkey',
    funFact: "Donkeys have an incredible memory and can recognize areas and other donkeys they were with up to 25 years ago.",
  },
  {
    id: 'turkey',
    name: "Turkey",
    emoji: '🦃',
    category: 'farm',
    imageUrl: '/assets/animals/turkey.jpg',
    soundType: 'turkey',
    funFact: "Wild turkeys can fly at speeds of up to 55 miles per hour over short distances.",
  },
  {
    id: 'llama',
    name: "Llama",
    emoji: '🦙',
    category: 'farm',
    imageUrl: '/assets/animals/llama.jpg',
    soundType: 'llama',
    funFact: "Llamas know their own limits. If you try to overload a llama with too much weight, it will simply lie down or refuse to move.",
  },
  {
    id: 'alpaca',
    name: "Alpaca",
    emoji: '🦙',
    category: 'farm',
    imageUrl: '/assets/animals/alpaca.jpg',
    soundType: 'alpaca',
    funFact: "Alpacas hum when they are curious, content, worried, bored, fearful, distressed or cautious.",
  },
  {
    id: 'goose',
    name: "Goose",
    emoji: '🪿',
    category: 'farm',
    imageUrl: '/assets/animals/goose.jpg',
    soundType: 'goose',
    funFact: "Geese fly in a V formation which allows them to fly 71% further than if they flew alone.",
  },
  {
    id: 'rooster',
    name: "Rooster",
    emoji: '🐓',
    category: 'farm',
    imageUrl: '/assets/animals/rooster.jpg',
    soundType: 'rooster',
    funFact: "A rooster will often crow to establish its territory and warn other roosters to stay away.",
  },
  {
    id: 'buffalo',
    name: "Water Buffalo",
    emoji: '🐃',
    category: 'farm',
    imageUrl: '/assets/animals/buffalo.jpg',
    soundType: 'buffalo',
    funFact: "Water buffalo are often used to plow rice paddies in Asia.",
  },
  {
    id: 'ox',
    name: "Ox",
    emoji: '🐂',
    category: 'farm',
    imageUrl: '/assets/animals/ox.jpg',
    soundType: 'ox',
    funFact: "Oxen are commonly castrated adult male cattle used as draft animals.",
  },
  {
    id: 'camel',
    name: "Camel",
    emoji: '🐪',
    category: 'farm',
    imageUrl: '/assets/animals/camel.jpg',
    soundType: 'camel',
    funFact: "Camels have three sets of eyelids and two rows of eyelashes to keep sand out of their eyes.",
  },
  {
    id: 'bactrian-camel',
    name: "Bactrian Camel",
    emoji: '🐫',
    category: 'farm',
    imageUrl: '/assets/animals/bactrian-camel.jpg',
    soundType: 'camel',
    funFact: "Unlike the dromedary, Bactrian camels have two humps.",
  },
  {
    id: 'rabbit',
    name: "Rabbit",
    emoji: '🐰',
    category: 'farm',
    imageUrl: '/assets/animals/rabbit.jpg',
    soundType: 'rabbit',
    funFact: "A rabbit’s teeth never stop growing, so they need to constantly chew to wear them down.",
  },
  {
    id: 'gorilla',
    name: "Gorilla",
    emoji: '🦍',
    category: 'wild',
    imageUrl: '/assets/animals/gorilla.jpg',
    soundType: 'gorilla',
    funFact: "Gorillas can catch human colds and other illnesses.",
  },
  {
    id: 'rhino',
    name: "Rhinoceros",
    emoji: '🦏',
    category: 'wild',
    imageUrl: '/assets/animals/rhino.jpg',
    soundType: 'rhino',
    funFact: "A rhinoceros horn is made of keratin, the same protein that makes up human hair and nails.",
  },
  {
    id: 'kangaroo',
    name: "Kangaroo",
    emoji: '🦘',
    category: 'wild',
    imageUrl: '/assets/animals/kangaroo.jpg',
    soundType: 'kangaroo',
    funFact: "Kangaroos cannot walk backwards because of the shape of their legs and their large muscular tail.",
  },
  {
    id: 'koala',
    name: "Koala",
    emoji: '🐨',
    category: 'wild',
    imageUrl: '/assets/animals/koala.jpg',
    soundType: 'koala',
    funFact: "Koalas sleep for up to 22 hours a day because their diet of eucalyptus leaves provides very little energy.",
  },
  {
    id: 'panda',
    name: "Giant Panda",
    emoji: '🐼',
    category: 'wild',
    imageUrl: '/assets/animals/panda.jpg',
    soundType: 'panda',
    funFact: "Giant pandas spend 10-16 hours a day eating bamboo.",
  },
  {
    id: 'sloth',
    name: "Sloth",
    emoji: '🦥',
    category: 'wild',
    imageUrl: '/assets/animals/sloth.jpg',
    soundType: 'sloth',
    funFact: "Sloths are so slow that algae can actually grow on their fur.",
  },
  {
    id: 'leopard',
    name: "Leopard",
    emoji: '🐆',
    category: 'wild',
    imageUrl: '/assets/animals/leopard.jpg',
    soundType: 'leopard',
    funFact: "Leopards are excellent climbers and often drag their prey up into trees to keep it safe from scavengers.",
  },
  {
    id: 'hyena',
    name: "Hyena",
    emoji: '🐆',
    category: 'wild',
    imageUrl: '/assets/animals/hyena.jpg',
    soundType: 'hyena',
    funFact: "Spotted hyenas are more closely related to cats than dogs, despite their dog-like appearance.",
  },
  {
    id: 'meerkat',
    name: "Meerkat",
    emoji: '🦦',
    category: 'wild',
    imageUrl: '/assets/animals/meerkat.jpg',
    soundType: 'meerkat',
    funFact: "Meerkats are immune to venom from many snakes and scorpions.",
  },
  {
    id: 'mongoose',
    name: "Mongoose",
    emoji: '🦦',
    category: 'wild',
    imageUrl: '/assets/animals/mongoose.jpg',
    soundType: 'mongoose',
    funFact: "Some species of mongoose are known for their ability to fight and kill venomous snakes.",
  },
  {
    id: 'fox',
    name: "Fox",
    emoji: '🦊',
    category: 'wild',
    imageUrl: '/assets/animals/fox.jpg',
    soundType: 'fox',
    funFact: "Foxes use the Earth’s magnetic field to hunt, judging the distance and direction of their prey before pouncing.",
  },
  {
    id: 'raccoon',
    name: "Raccoon",
    emoji: '🦝',
    category: 'wild',
    imageUrl: '/assets/animals/raccoon.jpg',
    soundType: 'raccoon',
    funFact: "Raccoons have highly sensitive hands that become even more sensitive when wet.",
  },
  {
    id: 'moose',
    name: "Moose",
    emoji: '🦌',
    category: 'wild',
    imageUrl: '/assets/animals/moose.jpg',
    soundType: 'moose',
    funFact: "Moose are excellent swimmers and can dive up to 5 meters to feed on aquatic plants.",
  },
  {
    id: 'deer',
    name: "Deer",
    emoji: '🦌',
    category: 'wild',
    imageUrl: '/assets/animals/deer.jpg',
    soundType: 'deer',
    funFact: "Male deer grow new antlers every year, which are covered in a fuzzy skin called velvet.",
  },
  {
    id: 'reindeer',
    name: "Reindeer",
    emoji: '🦌',
    category: 'wild',
    imageUrl: '/assets/animals/reindeer.jpg',
    soundType: 'reindeer',
    funFact: "Reindeer are the only deer species where both males and females grow antlers.",
  },
  {
    id: 'boar',
    name: "Wild Boar",
    emoji: '🐗',
    category: 'wild',
    imageUrl: '/assets/animals/boar.jpg',
    soundType: 'boar',
    funFact: "Wild boars use their hardened snouts to dig for roots and tubers in the ground.",
  },
  {
    id: 'bison',
    name: "Bison",
    emoji: '🦬',
    category: 'wild',
    imageUrl: '/assets/animals/bison.jpg',
    soundType: 'bison',
    funFact: "Bison can weigh up to 2,000 pounds and run at speeds of up to 35 miles per hour.",
  },
  {
    id: 'badger',
    name: "Badger",
    emoji: '🦡',
    category: 'wild',
    imageUrl: '/assets/animals/badger.jpg',
    soundType: 'badger',
    funFact: "Badgers create complex underground burrow systems called setts, which can be centuries old.",
  },
  {
    id: 'hedgehog',
    name: "Hedgehog",
    emoji: '🦔',
    category: 'wild',
    imageUrl: '/assets/animals/hedgehog.jpg',
    soundType: 'hedgehog',
    funFact: "A hedgehog has between 5,000 and 7,000 quills on its back.",
  },
  {
    id: 'skunk',
    name: "Skunk",
    emoji: '🦨',
    category: 'wild',
    imageUrl: '/assets/animals/skunk.jpg',
    soundType: 'skunk',
    funFact: "Skunks can spray their stinky scent up to 10 feet away.",
  },
  {
    id: 'bat',
    name: "Bat",
    emoji: '🦇',
    category: 'wild',
    imageUrl: '/assets/animals/bat.jpg',
    soundType: 'bat',
    funFact: "Bats are the only mammals capable of true sustained flight.",
  },
  {
    id: 'monkey',
    name: "Monkey",
    emoji: '🐒',
    category: 'wild',
    imageUrl: '/assets/animals/monkey.jpg',
    soundType: 'monkey',
    funFact: "Capuchin monkeys use rocks as tools to crack open hard nuts.",
  },
  {
    id: 'orangutan',
    name: "Orangutan",
    emoji: '🦧',
    category: 'wild',
    imageUrl: '/assets/animals/orangutan.jpg',
    soundType: 'orangutan',
    funFact: "Orangutans share 96.4% of our genes and are highly intelligent apes.",
  },
  {
    id: 'lemur',
    name: "Lemur",
    emoji: '🐒',
    category: 'wild',
    imageUrl: '/assets/animals/lemur.jpg',
    soundType: 'lemur',
    funFact: "Lemurs are native only to the island of Madagascar.",
  },
  {
    id: 'baboon',
    name: "Baboon",
    emoji: '🐒',
    category: 'wild',
    imageUrl: '/assets/animals/baboon.jpg',
    soundType: 'baboon',
    funFact: "Baboons have dog-like muzzles and powerful jaws.",
  },
  {
    id: 'squirrel',
    name: "Squirrel",
    emoji: '🐿️',
    category: 'wild',
    imageUrl: '/assets/animals/squirrel.jpg',
    soundType: 'squirrel',
    funFact: "Squirrels plant thousands of new trees each year simply by forgetting where they buried their acorns.",
  },
  {
    id: 'chipmunk',
    name: "Chipmunk",
    emoji: '🐿️',
    category: 'wild',
    imageUrl: '/assets/animals/chipmunk.jpg',
    soundType: 'chipmunk',
    funFact: "A chipmunk can stuff its cheek pouches with food until they expand to three times the size of its head.",
  },
  {
    id: 'beaver',
    name: "Beaver",
    emoji: '🦫',
    category: 'wild',
    imageUrl: '/assets/animals/beaver.jpg',
    soundType: 'beaver',
    funFact: "Beavers have orange teeth because they contain iron, which makes them stronger for chewing wood.",
  },
  {
    id: 'armadillo',
    name: "Armadillo",
    emoji: '🪖',
    category: 'wild',
    imageUrl: '/assets/animals/armadillo.jpg',
    soundType: 'armadillo',
    funFact: "Nine-banded armadillos nearly always give birth to four identical quadruplets.",
  },
  {
    id: 'wolverine',
    name: "Wolverine",
    emoji: '🐻',
    category: 'wild',
    imageUrl: '/assets/animals/wolverine.jpg',
    soundType: 'wolverine',
    funFact: "Wolverines have a reputation for ferocity and strength out of proportion to their size.",
  },
  {
    id: 'walrus',
    name: "Walrus",
    emoji: '🦭',
    category: 'sea',
    imageUrl: '/assets/animals/walrus.jpg',
    soundType: 'walrus',
    funFact: "Walruses use their long tusks to pull themselves out of the water and onto the ice.",
  },
  {
    id: 'seal',
    name: "Seal",
    emoji: '🦭',
    category: 'sea',
    imageUrl: '/assets/animals/seal.jpg',
    soundType: 'seal',
    funFact: "Seals can hold their breath for up to two hours underwater.",
  },
  {
    id: 'penguin',
    name: "Penguin",
    emoji: '🐧',
    category: 'sea',
    imageUrl: '/assets/animals/penguin.jpg',
    soundType: 'penguin',
    funFact: "Penguins possess a gland above their eyes that converts seawater into freshwater.",
  },
  {
    id: 'orca',
    name: "Orca (Killer Whale)",
    emoji: '🐋',
    category: 'sea',
    imageUrl: '/assets/animals/orca.jpg',
    soundType: 'orca',
    funFact: "Orcas are actually the largest species of the dolphin family.",
  },
  {
    id: 'beluga',
    name: "Beluga Whale",
    emoji: '🐳',
    category: 'sea',
    imageUrl: '/assets/animals/beluga.jpg',
    soundType: 'beluga',
    funFact: "Beluga whales can change the shape of their bulbous foreheads, called \"melons,\" by blowing air around their sinuses.",
  },
  {
    id: 'humpback-whale',
    name: "Humpback Whale",
    emoji: '🐋',
    category: 'sea',
    imageUrl: '/assets/animals/humpback-whale.jpg',
    soundType: 'whale',
    funFact: "Humpback whales are known for their magical and complex songs, which can last for hours.",
  },
  {
    id: 'narwhal',
    name: "Narwhal",
    emoji: '🦄',
    category: 'sea',
    imageUrl: '/assets/animals/narwhal.jpg',
    soundType: 'whale',
    funFact: "The narwhal’s \"horn\" is actually an elongated upper left canine tooth.",
  },
  {
    id: 'manatee',
    name: "Manatee",
    emoji: '🧜',
    category: 'sea',
    imageUrl: '/assets/animals/manatee.jpg',
    soundType: 'manatee',
    funFact: "Manatees are closely related to elephants, not to other marine mammals like whales or dolphins.",
  },
  {
    id: 'crab',
    name: "Crab",
    emoji: '🦀',
    category: 'sea',
    imageUrl: '/assets/animals/crab.jpg',
    soundType: 'crab',
    funFact: "Crabs communicate with each other by drumming or waving their pincers.",
  },
  {
    id: 'lobster',
    name: "Lobster",
    emoji: '🦞',
    category: 'sea',
    imageUrl: '/assets/animals/lobster.jpg',
    soundType: 'lobster',
    funFact: "Lobsters chew their food in their stomachs, not in their mouths.",
  },
  {
    id: 'shrimp',
    name: "Shrimp",
    emoji: '🦐',
    category: 'sea',
    imageUrl: '/assets/animals/shrimp.jpg',
    soundType: 'shrimp',
    funFact: "The heart of a shrimp is located in its head.",
  },
  {
    id: 'squid',
    name: "Squid",
    emoji: '🦑',
    category: 'sea',
    imageUrl: '/assets/animals/squid.jpg',
    soundType: 'squid',
    funFact: "Giant squids have eyes the size of dinner plates, the largest in the animal kingdom.",
  },
  {
    id: 'stingray',
    name: "Stingray",
    emoji: '🐡',
    category: 'sea',
    imageUrl: '/assets/animals/stingray.jpg',
    soundType: 'stingray',
    funFact: "Stingrays are closely related to sharks, and their skeletons are also made of cartilage.",
  },
  {
    id: 'seahorse',
    name: "Seahorse",
    emoji: '🐎',
    category: 'sea',
    imageUrl: '/assets/animals/seahorse.jpg',
    soundType: 'seahorse',
    funFact: "Male seahorses are the ones who carry and give birth to their young.",
  },
  {
    id: 'starfish',
    name: "Starfish",
    emoji: '⭐',
    category: 'sea',
    imageUrl: '/assets/animals/starfish.jpg',
    soundType: 'starfish',
    funFact: "Starfish can regenerate their own arms, and a single arm can regenerate a whole body.",
  },
  {
    id: 'coral',
    name: "Coral",
    emoji: '🪸',
    category: 'sea',
    imageUrl: '/assets/animals/coral.jpg',
    soundType: 'coral',
    funFact: "Coral reefs are actually made up of millions of tiny animals called polyps.",
  },
  {
    id: 'blowfish',
    name: "Pufferfish",
    emoji: '🐡',
    category: 'sea',
    imageUrl: '/assets/animals/blowfish.jpg',
    soundType: 'blowfish',
    funFact: "Pufferfish can inflate their bodies like balloons to make themselves harder for predators to swallow.",
  },
  {
    id: 'swan',
    name: "Swan",
    emoji: '🦢',
    category: 'birds',
    imageUrl: '/assets/animals/swan.jpg',
    soundType: 'swan',
    funFact: "Swans mate for life, and when they touch their beaks together, their necks form a heart shape.",
  },
  {
    id: 'peacock',
    name: "Peacock",
    emoji: '🦚',
    category: 'birds',
    imageUrl: '/assets/animals/peacock.jpg',
    soundType: 'peacock',
    funFact: "Only the males are called peacocks. Females are called peahens, and together they are peafowl.",
  },
  {
    id: 'pelican',
    name: "Pelican",
    emoji: '🦤',
    category: 'birds',
    imageUrl: '/assets/animals/pelican.jpg',
    soundType: 'pelican',
    funFact: "A pelican’s pouch can hold up to 3 gallons of water—more than its stomach can hold.",
  },
  {
    id: 'stork',
    name: "Stork",
    emoji: '🦩',
    category: 'birds',
    imageUrl: '/assets/animals/stork.jpg',
    soundType: 'stork',
    funFact: "Storks use their large bills to catch fish, frogs, and large insects.",
  },
  {
    id: 'emu',
    name: "Emu",
    emoji: '🦅',
    category: 'birds',
    imageUrl: '/assets/animals/emu.jpg',
    soundType: 'emu',
    funFact: "Emus cannot walk backwards.",
  },
  {
    id: 'woodpecker',
    name: "Woodpecker",
    emoji: '🦜',
    category: 'birds',
    imageUrl: '/assets/animals/woodpecker.jpg',
    soundType: 'woodpecker',
    funFact: "Woodpeckers can peck at wood up to 20 times per second.",
  },
  {
    id: 'hummingbird',
    name: "Hummingbird",
    emoji: '🐦',
    category: 'birds',
    imageUrl: '/assets/animals/hummingbird.jpg',
    soundType: 'hummingbird',
    funFact: "Hummingbirds are the only birds that can fly backwards.",
  },
  {
    id: 'pigeon',
    name: "Pigeon",
    emoji: '🐦',
    category: 'birds',
    imageUrl: '/assets/animals/pigeon.jpg',
    soundType: 'pigeon',
    funFact: "Pigeons can recognize themselves in a mirror.",
  },
  {
    id: 'crow',
    name: "Crow",
    emoji: '🐦‍⬛',
    category: 'birds',
    imageUrl: '/assets/animals/crow.jpg',
    soundType: 'crow',
    funFact: "Crows can recognize individual human faces and remember them for years.",
  },
  {
    id: 'raven',
    name: "Raven",
    emoji: '🐦‍⬛',
    category: 'birds',
    imageUrl: '/assets/animals/raven.jpg',
    soundType: 'raven',
    funFact: "Ravens are highly playful and have been observed playing in the snow and sliding down hills.",
  },
  {
    id: 'dove',
    name: "Dove",
    emoji: '🕊️',
    category: 'birds',
    imageUrl: '/assets/animals/dove.jpg',
    soundType: 'dove',
    funFact: "Doves produce a special milk, called crop milk, to feed their chicks.",
  },
  {
    id: 'seagull',
    name: "Seagull",
    emoji: '🪶',
    category: 'birds',
    imageUrl: '/assets/animals/seagull.jpg',
    soundType: 'seagull',
    funFact: "Seagulls have a special pair of glands above their eyes that flushes salt from their systems.",
  },
  {
    id: 'canary',
    name: "Canary",
    emoji: '🐥',
    category: 'birds',
    imageUrl: '/assets/animals/canary.jpg',
    soundType: 'canary',
    funFact: "Canaries were once used in coal mines to detect toxic gases.",
  },
  {
    id: 'parrot',
    name: "Parrot",
    emoji: '🦜',
    category: 'birds',
    imageUrl: '/assets/animals/parrot.jpg',
    soundType: 'parrot',
    funFact: "Some parrot species can live to be over 80 years old.",
  },
  {
    id: 'vulture',
    name: "Vulture",
    emoji: '🦅',
    category: 'birds',
    imageUrl: '/assets/animals/vulture.jpg',
    soundType: 'vulture',
    funFact: "Vultures have stomach acid that is so corrosive it can digest anthrax and botulism toxins without harm.",
  },
  {
    id: 'falcon',
    name: "Falcon",
    emoji: '🦅',
    category: 'birds',
    imageUrl: '/assets/animals/falcon.jpg',
    soundType: 'falcon',
    funFact: "The peregrine falcon is the fastest bird in the world, capable of diving at over 240 mph.",
  },
  {
    id: 'hawk',
    name: "Hawk",
    emoji: '🦅',
    category: 'birds',
    imageUrl: '/assets/animals/hawk.jpg',
    soundType: 'hawk',
    funFact: "A hawk’s vision is roughly eight times sharper than a human’s.",
  },
  {
    id: 'turkey-vulture',
    name: "Turkey Vulture",
    emoji: '🦅',
    category: 'birds',
    imageUrl: '/assets/animals/turkey-vulture.jpg',
    soundType: 'vulture',
    funFact: "Turkey vultures find their food primarily by smell, rather than sight.",
  },
  {
    id: 'butterfly',
    name: "Butterfly",
    emoji: '🦋',
    category: 'bugs',
    imageUrl: '/assets/animals/butterfly.jpg',
    soundType: 'butterfly',
    funFact: "Butterflies taste with their feet to find the right plants for their caterpillars.",
  },
  {
    id: 'bee',
    name: "Bee",
    emoji: '🐝',
    category: 'bugs',
    imageUrl: '/assets/animals/bee.jpg',
    soundType: 'bee',
    funFact: "A honey bee will visit about 50 to 100 flowers during one collection trip.",
  },
  {
    id: 'ladybug',
    name: "Ladybug",
    emoji: '🐞',
    category: 'bugs',
    imageUrl: '/assets/animals/ladybug.jpg',
    soundType: 'ladybug',
    funFact: "Ladybugs can eat up to 5,000 insects in their lifetime.",
  },
  {
    id: 'spider',
    name: "Spider",
    emoji: '🕷️',
    category: 'bugs',
    imageUrl: '/assets/animals/spider.jpg',
    soundType: 'spider',
    funFact: "Spider silk is incredibly strong, and is proportionally stronger than steel.",
  },
  {
    id: 'scorpion',
    name: "Scorpion",
    emoji: '🦂',
    category: 'bugs',
    imageUrl: '/assets/animals/scorpion.jpg',
    soundType: 'scorpion',
    funFact: "Scorpions glow under ultraviolet light.",
  },
  {
    id: 'fly',
    name: "Fly",
    emoji: '🪰',
    category: 'bugs',
    imageUrl: '/assets/animals/fly.jpg',
    soundType: 'fly',
    funFact: "Flies hum in the key of F.",
  },
  {
    id: 'beetle',
    name: "Beetle",
    emoji: '🪲',
    category: 'bugs',
    imageUrl: '/assets/animals/beetle.jpg',
    soundType: 'beetle',
    funFact: "One out of every four animal species on Earth is a beetle.",
  },
  {
    id: 'cricket',
    name: "Cricket",
    emoji: '🦗',
    category: 'bugs',
    imageUrl: '/assets/animals/cricket.jpg',
    soundType: 'cricket',
    funFact: "You can estimate the temperature by counting a cricket’s chirps.",
  },
  {
    id: 'caterpillar',
    name: "Caterpillar",
    emoji: '🐛',
    category: 'bugs',
    imageUrl: '/assets/animals/caterpillar.jpg',
    soundType: 'caterpillar',
    funFact: "Caterpillars have 12 eyes, but their vision is very poor.",
  },
  {
    id: 'snail',
    name: "Snail",
    emoji: '🐌',
    category: 'bugs',
    imageUrl: '/assets/animals/snail.jpg',
    soundType: 'snail',
    funFact: "A snail can sleep for up to 3 years.",
  },
  {
    id: 'worm',
    name: "Worm",
    emoji: '🪱',
    category: 'bugs',
    imageUrl: '/assets/animals/worm.jpg',
    soundType: 'worm',
    funFact: "Earthworms have five hearts.",
  },
  {
    id: 'mouse',
    name: "Mouse",
    emoji: '🐭',
    category: 'wild',
    imageUrl: '/assets/animals/mouse.jpg',
    soundType: 'mouse',
    funFact: "A mouse’s teeth never stop growing, so they have to gnaw on things to wear them down.",
  },
  {
    id: 'hamster',
    name: "Hamster",
    emoji: '🐹',
    category: 'wild',
    imageUrl: '/assets/animals/hamster.jpg',
    soundType: 'hamster',
    funFact: "Hamsters are crepuscular, meaning they are most active during the twilight hours.",
  },
  {
    id: 'guinea-pig',
    name: "Guinea Pig",
    emoji: '🐹',
    category: 'wild',
    imageUrl: '/assets/animals/guinea-pig.jpg',
    soundType: 'guinea_pig',
    funFact: "When happy, guinea pigs often jump straight up in the air, a move called \"popcorning\".",
  },
  {
    id: 'ferret',
    name: "Ferret",
    emoji: '🦦',
    category: 'wild',
    imageUrl: '/assets/animals/ferret.jpg',
    soundType: 'ferret',
    funFact: "Ferrets love to sleep and can snooze for up to 18 hours a day.",
  },
  {
    id: 'chinchilla',
    name: "Chinchilla",
    emoji: '🐭',
    category: 'wild',
    imageUrl: '/assets/animals/chinchilla.jpg',
    soundType: 'chinchilla',
    funFact: "Chinchillas take dust baths to clean themselves because their fur is too dense for water.",
  },
  {
    id: 'snake',
    name: "Snake",
    emoji: '🐍',
    category: 'wild',
    imageUrl: '/assets/animals/snake.jpg',
    soundType: 'snake',
    funFact: "Snakes use their tongues to smell their surroundings.",
  },
  {
    id: 'lizard',
    name: "Lizard",
    emoji: '🦎',
    category: 'wild',
    imageUrl: '/assets/animals/lizard.jpg',
    soundType: 'lizard',
    funFact: "Many lizards can detach their tails to escape from predators, and some can grow them back.",
  },
  {
    id: 'iguana',
    name: "Iguana",
    emoji: '🦎',
    category: 'wild',
    imageUrl: '/assets/animals/iguana.jpg',
    soundType: 'iguana',
    funFact: "Iguanas have a \"third eye\" on top of their head to detect shadows of predatory birds.",
  },
  {
    id: 'chameleon',
    name: "Chameleon",
    emoji: '🦎',
    category: 'wild',
    imageUrl: '/assets/animals/chameleon.jpg',
    soundType: 'chameleon',
    funFact: "Chameleons change color not just for camouflage, but also to regulate their temperature or show their mood.",
  },
  {
    id: 'crocodile',
    name: "Crocodile",
    emoji: '🐊',
    category: 'wild',
    imageUrl: '/assets/animals/crocodile.jpg',
    soundType: 'crocodile',
    funFact: "Crocodiles can replace each of their 80 teeth up to 50 times in their lifetime.",
  },
  {
    id: 'alligator',
    name: "Alligator",
    emoji: '🐊',
    category: 'wild',
    imageUrl: '/assets/animals/alligator.jpg',
    soundType: 'alligator',
    funFact: "An alligator’s sex is determined by the temperature of the nest where its egg was incubated.",
  },
  {
    id: 'anteater',
    name: "Giant Anteater",
    emoji: '🐜',
    category: 'wild',
    imageUrl: '/assets/animals/anteater.jpg',
    soundType: 'anteater',
    funFact: "Giant anteaters can consume up to 30,000 ants and termites every single day with their two-foot-long tongue.",
  },
  {
    id: 'antelope',
    name: "Antelope",
    emoji: '🦌',
    category: 'wild',
    imageUrl: '/assets/animals/antelope.jpg',
    soundType: 'antelope',
    funFact: "Antelopes have keen senses and can run at tremendous speeds of over 80 kilometres per hour to escape predators.",
  },
  {
    id: 'coyote',
    name: "Coyote",
    emoji: '🐺',
    category: 'wild',
    imageUrl: '/assets/animals/coyote.jpg',
    soundType: 'coyote',
    funFact: "Coyotes communicate using a variety of yips, howls, and barks that can be heard miles across the desert.",
  },
  {
    id: 'jackal',
    name: "Golden Jackal",
    emoji: '🐺',
    category: 'wild',
    imageUrl: '/assets/animals/jackal.jpg',
    soundType: 'jackal',
    funFact: "Jackals are resourceful omnivores and often form lifelong monogamous pairs.",
  },
  {
    id: 'lynx',
    name: "Eurasian Lynx",
    emoji: '🐾',
    category: 'wild',
    imageUrl: '/assets/animals/lynx.jpg',
    soundType: 'lynx',
    funFact: "The Eurasian lynx has distinctive black tufts of hair on the tips of its ears that improve its sharp hearing.",
  },
  {
    id: 'pangolin',
    name: "Pangolin",
    emoji: '🪖',
    category: 'wild',
    imageUrl: '/assets/animals/pangolin.jpg',
    soundType: 'pangolin',
    funFact: "Pangolins are the only mammals in the world covered in tough keratin scales for protection.",
  },
  {
    id: 'porcupine',
    name: "Porcupine",
    emoji: '🦔',
    category: 'wild',
    imageUrl: '/assets/animals/porcupine.jpg',
    soundType: 'porcupine',
    funFact: "A single porcupine has over 30,000 sharp quills on its body that protect it from predators.",
  },
  {
    id: 'puma',
    name: "Puma",
    emoji: '🐆',
    category: 'wild',
    imageUrl: '/assets/animals/puma.jpg',
    soundType: 'puma',
    funFact: "Pumas can jump up to 18 feet into the air and leap distances of over 40 feet across rocky terrain.",
  },
  {
    id: 'red-panda',
    name: "Red Panda",
    emoji: '🐼',
    category: 'wild',
    imageUrl: '/assets/animals/red-panda.jpg',
    soundType: 'red_panda',
    funFact: "Red pandas use their bushy, ringed tails like cozy blankets to keep themselves warm in snowy mountain treetops.",
  },
  {
    id: 'snow-leopard',
    name: "Snow Leopard",
    emoji: '🐆',
    category: 'wild',
    imageUrl: '/assets/animals/snow-leopard.jpg',
    soundType: 'snow_leopard',
    funFact: "Snow leopards have wide, fur-covered paws that act like natural snowshoes on steep icy mountain slopes.",
  },
  {
    id: 'tapir',
    name: "South American Tapir",
    emoji: '🦛',
    category: 'wild',
    imageUrl: '/assets/animals/tapir.jpg',
    soundType: 'tapir',
    funFact: "Tapirs use their flexible, prehensile snouts like an elephant trunk to grab leaves and fruits in dense rainforests.",
  },
  {
    id: 'elk',
    name: "Majestic Elk",
    emoji: '🦌',
    category: 'wild',
    imageUrl: '/assets/animals/elk.jpg',
    soundType: 'elk',
    funFact: "Male elks grow majestic sets of antlers that can weigh up to 40 pounds and span five feet across.",
  },
  {
    id: 'gazelle',
    name: "Gazelle",
    emoji: '🦌',
    category: 'wild',
    imageUrl: '/assets/animals/gazelle.jpg',
    soundType: 'gazelle',
    funFact: "Gazelles practice a high-bounding leap called stotting to show predators how energetic and swift they are.",
  },
  {
    id: 'mole',
    name: "Star-nosed Mole",
    emoji: '🐾',
    category: 'wild',
    imageUrl: '/assets/animals/mole.jpg',
    soundType: 'mole',
    funFact: "The star-nosed mole can identify and eat food in as little as 227 milliseconds, making it the fastest-eating mammal on Earth.",
  },
  {
    id: 'sea-lion',
    name: "Sea Lion",
    emoji: '🦭',
    category: 'sea',
    imageUrl: '/assets/animals/sea-lion.jpg',
    soundType: 'sea_lion',
    funFact: "Sea lions are agile swimmers and can dive to depths of over 300 metres in search of fish and squid.",
  },
  {
    id: 'manta-ray',
    name: "Manta Ray",
    emoji: '🐟',
    category: 'sea',
    imageUrl: '/assets/animals/manta-ray.jpg',
    soundType: 'manta_ray',
    funFact: "Manta rays have the largest brain-to-body ratio of all fish and are known to be curious and intelligent creatures.",
  },
  {
    id: 'sperm-whale',
    name: "Sperm Whale",
    emoji: '🐋',
    category: 'sea',
    imageUrl: '/assets/animals/sperm-whale.jpg',
    soundType: 'sperm_whale',
    funFact: "Sperm whales have the largest brain of any known animal species and can dive over 2,000 metres deep.",
  },
  {
    id: 'man-of-war',
    name: "Portuguese Man o' War",
    emoji: '🪼',
    category: 'sea',
    imageUrl: '/assets/animals/man-of-war.jpg',
    soundType: 'man_of_war',
    funFact: "The Portuguese man o' war is not a single animal, but a floating colonial organism composed of specialized polyps.",
  },
  {
    id: 'cockatoo',
    name: "Cockatoo",
    emoji: '🦜',
    category: 'birds',
    imageUrl: '/assets/animals/cockatoo.jpg',
    soundType: 'cockatoo',
    funFact: "Cockatoos have expressive head crests that raise and flare when they are excited, curious, or alarmed.",
  },
  {
    id: 'kingfisher',
    name: "Kingfisher",
    emoji: '🐦',
    category: 'birds',
    imageUrl: '/assets/animals/kingfisher.jpg',
    soundType: 'kingfisher',
    funFact: "Kingfishers dive at speeds of up to 40 kilometres per hour into crystal clear water to catch small fish without splashing.",
  },
  {
    id: 'gecko',
    name: "Leopard Gecko",
    emoji: '🦎',
    category: 'wild',
    imageUrl: '/assets/animals/gecko.jpg',
    soundType: 'gecko',
    funFact: "Leopard geckos store extra fat and water in their thick tails to survive in dry habitats.",
  },
  {
    id: 'python',
    name: "Green Tree Python",
    emoji: '🐍',
    category: 'wild',
    imageUrl: '/assets/animals/python.jpg',
    soundType: 'python',
    funFact: "Green tree pythons curl themselves gracefully in tight rings over horizontal tree branches to sleep during the day.",
  },
  {
    id: 'salamander',
    name: "Fire Salamander",
    emoji: '🦎',
    category: 'wild',
    imageUrl: '/assets/animals/salamander.jpg',
    soundType: 'salamander',
    funFact: "Fire salamanders have vibrant black and yellow markings that warn predators of their toxic skin secretions.",
  },
  {
    id: 'toad',
    name: "Common Toad",
    emoji: '🐸',
    category: 'wild',
    imageUrl: '/assets/animals/toad.jpg',
    soundType: 'toad',
    funFact: "Toads have bumpy, dry skin and can puff up their bodies to look bigger when threatened.",
  },
  {
    id: 'tortoise',
    name: "Giant Tortoise",
    emoji: '🐢',
    category: 'wild',
    imageUrl: '/assets/animals/tortoise.jpg',
    soundType: 'tortoise',
    funFact: "Galapagos giant tortoises can live for over 150 years and can survive for months without food or fresh water.",
  },
];
