export type AnimalCategory = 'all' | 'farm' | 'wild' | 'sea' | 'birds';

export interface Animal {
  id: string;
  name: string;
  emoji: string;
  category: 'farm' | 'wild' | 'sea' | 'birds';
  imageUrl: string;
  soundType: string;
  funFact: string;
}

export interface Habitat {
  id: AnimalCategory;
  name: string;
  emoji: string;
  bgGradient: string;
}

export const HABITATS: Habitat[] = [
  {
    id: 'all',
    name: 'All',
    emoji: '🐾',
    bgGradient: 'bg-slate-50',
  },
  {
    id: 'farm',
    name: 'Farm',
    emoji: '🚜',
    bgGradient: 'bg-emerald-50/40',
  },
  {
    id: 'wild',
    name: 'Wild',
    emoji: '🦁',
    bgGradient: 'bg-amber-50/40',
  },
  {
    id: 'sea',
    name: 'Sea',
    emoji: '🌊',
    bgGradient: 'bg-sky-50/40',
  },
  {
    id: 'birds',
    name: 'Birds',
    emoji: '🦜',
    bgGradient: 'bg-rose-50/40',
  },
];

export const ANIMALS: Animal[] = [
  // ==================== FARM ANIMALS ====================
  {
    id: 'cow',
    name: 'Cow',
    emoji: '🐮',
    category: 'farm',
    imageUrl: 'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?auto=format&fit=crop&w=1200&q=85',
    soundType: 'cow',
    funFact: 'Cows eat grass and produce fresh milk.',
  },
  {
    id: 'pig',
    name: 'Pig',
    emoji: '🐷',
    category: 'farm',
    imageUrl: 'https://images.unsplash.com/photo-1516467508483-a7212febe31a?auto=format&fit=crop&w=1200&q=85',
    soundType: 'pig',
    funFact: 'Pigs are highly intelligent animals with an excellent sense of smell.',
  },
  {
    id: 'sheep',
    name: 'Sheep',
    emoji: '🐑',
    category: 'farm',
    imageUrl: 'https://images.unsplash.com/photo-1500595046743-cd271d694d30?auto=format&fit=crop&w=1200&q=85',
    soundType: 'sheep',
    funFact: 'Sheep have thick wool coats that keep them warm in cold weather.',
  },
  {
    id: 'horse',
    name: 'Horse',
    emoji: '🐴',
    category: 'farm',
    imageUrl: 'https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?auto=format&fit=crop&w=1200&q=85',
    soundType: 'horse',
    funFact: 'Horses can sleep both lying down and standing up.',
  },
  {
    id: 'duck',
    name: 'Duck',
    emoji: '🦆',
    category: 'farm',
    imageUrl: 'https://images.unsplash.com/photo-1598439210625-5067c578f3f6?auto=format&fit=crop&w=1200&q=85',
    soundType: 'duck',
    funFact: 'Ducks have waterproof feathers and webbed feet for swimming.',
  },
  {
    id: 'chicken',
    name: 'Chicken',
    emoji: '🐔',
    category: 'farm',
    imageUrl: 'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?auto=format&fit=crop&w=1200&q=85',
    soundType: 'chicken',
    funFact: 'Chickens communicate with over thirty distinct vocal sounds.',
  },
  {
    id: 'dog',
    name: 'Dog',
    emoji: '🐶',
    category: 'farm',
    imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=1200&q=85',
    soundType: 'dog',
    funFact: 'Dogs have an extraordinary sense of smell up to 100,000 times stronger than humans.',
  },
  {
    id: 'cat',
    name: 'Cat',
    emoji: '🐱',
    category: 'farm',
    imageUrl: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=1200&q=85',
    soundType: 'cat',
    funFact: 'Cats can rotate their ears 180 degrees to detect faint sounds.',
  },
  {
    id: 'frog',
    name: 'Frog',
    emoji: '🐸',
    category: 'farm',
    imageUrl: 'https://images.unsplash.com/photo-1546853020-ca4909aef454?auto=format&fit=crop&w=1200&q=85',
    soundType: 'frog',
    funFact: 'Frogs absorb water directly through their skin rather than drinking it.',
  },

  // ==================== WILD ANIMALS ====================
  {
    id: 'lion',
    name: 'Lion',
    emoji: '🦁',
    category: 'wild',
    imageUrl: 'https://images.unsplash.com/photo-1614027164847-1b28cfe1df60?auto=format&fit=crop&w=1200&q=85',
    soundType: 'lion',
    funFact: 'A lion roar can be heard from up to eight kilometres away.',
  },
  {
    id: 'tiger',
    name: 'Tiger',
    emoji: '🐯',
    category: 'wild',
    imageUrl: 'https://images.unsplash.com/photo-1561731216-c3a4d99437d5?auto=format&fit=crop&w=1200&q=85',
    soundType: 'tiger',
    funFact: 'Tigers are the largest cat species and are strong swimmers.',
  },
  {
    id: 'elephant',
    name: 'Elephant',
    emoji: '🐘',
    category: 'wild',
    imageUrl: 'https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?auto=format&fit=crop&w=1200&q=85',
    soundType: 'elephant',
    funFact: 'Elephants are the largest land animals and have remarkable memories.',
  },
  {
    id: 'giraffe',
    name: 'Giraffe',
    emoji: '🦒',
    category: 'wild',
    imageUrl: 'https://images.unsplash.com/photo-1547721064-da6cfb341d50?auto=format&fit=crop&w=1200&q=85',
    soundType: 'giraffe',
    funFact: 'Giraffes are the tallest mammals in the world, with legs longer than most humans.',
  },
  {
    id: 'cheetah',
    name: 'Cheetah',
    emoji: '🐆',
    category: 'wild',
    imageUrl: 'https://images.unsplash.com/photo-1534177616072-ef7dc120449d?auto=format&fit=crop&w=1200&q=85',
    soundType: 'cheetah',
    funFact: 'Cheetahs are the fastest land animals, reaching speeds of up to 110 kilometres per hour.',
  },
  {
    id: 'hippo',
    name: 'Hippo',
    emoji: '🦛',
    category: 'wild',
    imageUrl: 'https://images.unsplash.com/photo-1574063413132-355dbfd83e23?auto=format&fit=crop&w=1200&q=85',
    soundType: 'hippo',
    funFact: 'Hippos spend most of the day submerged in water to keep their skin cool.',
  },
  {
    id: 'chimp',
    name: 'Chimpanzee',
    emoji: '🐒',
    category: 'wild',
    imageUrl: 'https://images.unsplash.com/photo-1540573133985-87b6da6d54a9?auto=format&fit=crop&w=1200&q=85',
    soundType: 'monkey',
    funFact: 'Chimpanzees use tools such as sticks and stones to find food.',
  },
  {
    id: 'zebra',
    name: 'Zebra',
    emoji: '🦓',
    category: 'wild',
    imageUrl: 'https://images.unsplash.com/photo-1526095179574-86e545346ae6?auto=format&fit=crop&w=1200&q=85',
    soundType: 'zebra',
    funFact: 'Every zebra has a completely unique pattern of black and white stripes.',
  },
  {
    id: 'bear',
    name: 'Bear',
    emoji: '🐻',
    category: 'wild',
    imageUrl: 'https://images.unsplash.com/photo-1530595467537-0b5996c41f2d?auto=format&fit=crop&w=1200&q=85',
    soundType: 'bear',
    funFact: 'Bears have an acute sense of smell and can hibernate through winter.',
  },
  {
    id: 'wolf',
    name: 'Wolf',
    emoji: '🐺',
    category: 'wild',
    imageUrl: 'https://images.unsplash.com/photo-1564865878688-9a244444042a?auto=format&fit=crop&w=1200&q=85',
    soundType: 'wolf',
    funFact: 'Wolves live and hunt in family packs led by an alpha pair.',
  },

  // ==================== SEA ANIMALS ====================
  {
    id: 'dolphin',
    name: 'Dolphin',
    emoji: '🐬',
    category: 'sea',
    imageUrl: 'https://images.unsplash.com/photo-1570481662006-a3a1374699e8?auto=format&fit=crop&w=1200&q=85',
    soundType: 'dolphin',
    funFact: 'Dolphins use echolocation clicks to navigate and hunt in murky water.',
  },
  {
    id: 'blue-whale',
    name: 'Blue Whale',
    emoji: '🐋',
    category: 'sea',
    imageUrl: 'https://images.unsplash.com/photo-1568430462989-44163eb1752f?auto=format&fit=crop&w=1200&q=85',
    soundType: 'whale',
    funFact: 'The blue whale is the largest known animal ever to have lived on Earth.',
  },
  {
    id: 'clownfish',
    name: 'Clownfish',
    emoji: '🐠',
    category: 'sea',
    imageUrl: 'https://images.unsplash.com/photo-1535591273668-578e31182c4f?auto=format&fit=crop&w=1200&q=85',
    soundType: 'clownfish',
    funFact: 'Clownfish have a special mucus coat that protects them from sea anemone stings.',
  },
  {
    id: 'sea-turtle',
    name: 'Sea Turtle',
    emoji: '🐢',
    category: 'sea',
    imageUrl: 'https://images.unsplash.com/photo-1544551763-77ef2d0cfc6c?auto=format&fit=crop&w=1200&q=85',
    soundType: 'turtle',
    funFact: 'Sea turtles can hold their breath underwater for several hours.',
  },
  {
    id: 'shark',
    name: 'Shark',
    emoji: '🦈',
    category: 'sea',
    imageUrl: 'https://images.unsplash.com/photo-1560275619-4662e36fa65c?auto=format&fit=crop&w=1200&q=85',
    soundType: 'shark',
    funFact: 'Sharks have skeletons made entirely of cartilage rather than bone.',
  },
  {
    id: 'octopus',
    name: 'Octopus',
    emoji: '🐙',
    category: 'sea',
    imageUrl: 'https://images.unsplash.com/photo-1545671913-b89ac1b4ac10?auto=format&fit=crop&w=1200&q=85',
    soundType: 'octopus',
    funFact: 'An octopus has three hearts and blue copper-based blood.',
  },
  {
    id: 'sea-otter',
    name: 'Sea Otter',
    emoji: '🦦',
    category: 'sea',
    imageUrl: 'https://images.unsplash.com/photo-1578328819058-b69f3a3b0f6b?auto=format&fit=crop&w=1200&q=85',
    soundType: 'otter',
    funFact: 'Sea otters hold paws while floating to prevent drifting apart in ocean currents.',
  },
  {
    id: 'jellyfish',
    name: 'Jellyfish',
    emoji: '🪼',
    category: 'sea',
    imageUrl: 'https://images.unsplash.com/photo-1508873696983-2df5293cb325?auto=format&fit=crop&w=1200&q=85',
    soundType: 'jellyfish',
    funFact: 'Jellyfish are made of 95% water and have existed for over 500 million years.',
  },

  // ==================== BIRDS ====================
  {
    id: 'toucan',
    name: 'Toucan',
    emoji: '🦚',
    category: 'birds',
    imageUrl: 'https://images.unsplash.com/photo-1550853024-fae8dd4be47f?auto=format&fit=crop&w=1200&q=85',
    soundType: 'toucan',
    funFact: 'A toucan bill is light and hollow, helping regulate its body temperature.',
  },
  {
    id: 'macaw',
    name: 'Macaw',
    emoji: '🦜',
    category: 'birds',
    imageUrl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?auto=format&fit=crop&w=1200&q=85',
    soundType: 'macaw',
    funFact: 'Macaws can live for over 50 years and are known for mimicry and intelligence.',
  },
  {
    id: 'flamingo',
    name: 'Flamingo',
    emoji: '🦩',
    category: 'birds',
    imageUrl: 'https://images.unsplash.com/photo-1539418561314-565804e349c0?auto=format&fit=crop&w=1200&q=85',
    soundType: 'flamingo',
    funFact: 'Flamingos get their pink color from natural pigments in their diet.',
  },
  {
    id: 'owl',
    name: 'Owl',
    emoji: '🦉',
    category: 'birds',
    imageUrl: 'https://images.unsplash.com/photo-1543549790-8b5f4a028cfb?auto=format&fit=crop&w=1200&q=85',
    soundType: 'owl',
    funFact: 'Owls have specialised feathers that enable near-silent flight.',
  },
  {
    id: 'eagle',
    name: 'Eagle',
    emoji: '🦅',
    category: 'birds',
    imageUrl: 'https://images.unsplash.com/photo-1611689342806-0863700ce1e4?auto=format&fit=crop&w=1200&q=85',
    soundType: 'eagle',
    funFact: 'Eagles have powerful vision capable of spotting prey miles away.',
  },
  {
    id: 'puffin',
    name: 'Puffin',
    emoji: '🐧',
    category: 'birds',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=85',
    soundType: 'puffin',
    funFact: 'Puffins can dive up to 60 metres underwater to catch small fish.',
  },
];
